const adminPassword = atob("Q2hhdEFwcElzQjNzdA==")
const maindevPassword = atob("SGVsbG9Xb3JsZEhlbGxvTWU")
const timmyPassword = atob("YmluZ2Jvbmd5b3VyZWdvbmU")
const jeffr3yPassword = atob("QnJ1aEJhbmFuYUJvdA")
const evanPassword = atob("RXZhbmlzYXdlc29tZTEyMyE")
const acPsw = atob("YWNkYWJlc3Qh")
console.log(adminPassword, maindevPassword, timmyPassword, jeffr3yPassword, evanPassword)
const adminPasswordKey = atob("QWRtaW5FbmNyeXB0UGhyYXNlMUA=")
console.log(adminPasswordKey)