'''
author: Rudra and 

created: 04-08-2021

copyrighted by Rudra and Tech 

'''


#normal
name = input("what is your name? ")
print("hello", name, "welcome to an app that is built by code with the tech_man and coder Rudra! click enter to continue")


if name == "Rudra":
  print("nice name buddy!!!")


input("")

#jokes:

input("click enter for a joke!")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")

print("white hat jr: the most important language is coding \n me: no! the most important language isnt coding! its english! for example: you cant just go to a caffe and say \n if ice coffee == 15 \n BUY \n if ice coffee == 1500+ \n get out")
print("they will kick you out if you say this!")

input("click enter for a joke!")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")

print("youtube: HELLO GUYS WELCOME TO THIS VIDEO \n IN THIS VIDEO I WILL TEACH HOW TO MAKE MINECRAFT!!!!! \n FIRST PIP INSTALL TECHAMNIAK \n I KNOW THIS IS MY NAME \n THEN WE JUST TYPE THIS CODE: \n from techmaniak import mc \n print(mc) \n IF THIS CODE DOESNT WORK YOU ARE USING THE OLDER VERSION OK EVERYBODY PEACE OUT ALSO SUBSCIBE")
print("*me trying this code* me: WHAT A SCAM!!!!!!!")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")


input("Click enter for a jok- for types of coders!")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")

print("types of coder: \n intern: always forgetting something \n junior coder the one who is learing \n senior coder doesnt codes any more also... i feel like they are lazy now a days in loackdown \n", name, "YES \n wth am i doing this should be a joke app NOOOO")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")


input("click enter for a joke")
print("")
print("")
print("")

print("3 aliens crashed there way to planet earth \n alien1 went to the school and learnt MEMEMEMEME \n alien2 went to the caffe and learnt knife and fork! alien3 went to the judge and learnt YES! \n so after a week a police man came and told \n police: WHO KILLED HIM? \n alien1: MEMEMEME \n police: with what? \n alien2: knife and fork! \n police: are you sure? \n alien3: YES")



print("will get updated by tech_man")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")

input("version 0.2 the gamers heaven! click enter for joke")

print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")

print("2020: >:) for gamers \n 2021: :_( ")

print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
input("CLICK ENTER FOR AD!!!!! |Enter|")

print("go sub to coder(Rudra); and code with the tech man you will find him in my subscription box!")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("mostly the update version 0.2 was some bug fixes")


code = input("code: ")

if code == 'coderrudra':
  print(":oooooooo")

else:
  print("ha! you got it wrong!!! >:)")

print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("21")
print("")
print("")
print(":|")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("How do you tell if a vampire is sick? By how much he is coffin!")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("Why does Humpty Dumpty love autumn?  Because Humpty Dumpty had a great fall!")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("What is the tallest building in the entire world?  The library, because it has so many stories")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("How do trees access the internet? They log in!")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("thats it for now CODERS")
input("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("let him play minecraft PEACEFULLY \n hehe get it? peacefull?")
print("")
print(":o i revived gamers heaven :ooooooooooooo")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("update 2.0 knock knock!")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")


print("knock knock \n whos there? \n FBI OPEN UP")


print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("Knock! Knock! \n Who's there? \n I am. I am \n who? You tell me!!")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("")
print("damn i hate knock knocks")