export function ThemePreview({ theme }) {
  if (!theme) {
    return null;
  }

  return (
    <svg
      width="280"
      height="160"
      viewBox="0 0 280 160"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <rect width="280" height="160" rx="2" stroke={theme.outlineDefault.color} fill={theme.backgroundRoot.color} />
      <rect
        x="10.5"
        y="10.5"
        width="79"
        height="139"
        rx="1.5"
        stroke={theme.backgroundHighest.color}
        fill={theme.backgroundDefault.color}
      />
      <rect
        x="100.5"
        y="10.5"
        width="169"
        height="139"
        rx="1.5"
        stroke={theme.backgroundHighest.color}
        fill={theme.backgroundDefault.color}
      />
      <rect
        x="110"
        y="20"
        width="130"
        height="10"
        rx="2"
        fill={theme.foregroundDefault.color}
      />
      <rect
        x="20"
        y="20"
        width="60"
        height="10"
        rx="2"
        fill={theme.foregroundDimmest.color}
      />
      <rect
        x="110"
        y="38"
        width="90"
        height="10"
        rx="2"
        fill={theme.foregroundDimmest.color}
      />
      <rect
        x="20"
        y="38"
        width="42"
        height="10"
        rx="2"
        fill={theme.foregroundDimmest.color}
      />
      <rect
        x="20"
        y="125"
        width="60"
        height="15"
        rx="4"
        fill={theme.accentPrimaryDefault.color}
      />
      <rect
        x="110"
        y="74"
        width="66"
        height="10"
        rx="2"
        fill={theme.outlineDefault.color}
      />
      <rect
        x="110"
        y="56"
        width="111"
        height="10"
        rx="2"
        fill={theme.accentNegativeDefault.color}
      />
      <rect
        x="110"
        y="92"
        width="95"
        height="10"
        rx="2"
        fill={theme.accentPositiveDefault.color}
      />
      <rect
        x="20"
        y="56"
        width="48"
        height="10"
        rx="2"
        fill={theme.foregroundDimmest.color}
      />
    </svg>
  );
}