import time
# ChatBot 0.8
print("Trixi: how are you?")
anr = input("Enter Here: ")
print("")
print("alright")
time.sleep(1)
print("Loading...")
time.sleep(2)
print("")
print("Trixi: \n1 - tell me a joke \n2 - force quit \n3 - quit \n4 - bot name \n5 - system info \n6 - chat")
print("")
anr = input("Enter Here: ")
if anr == "1":
    print(
        "Astronomers got tired of watching the moon go round the earth for 24 hours"
    )
    time.sleep(3.5)
    print("So they called it a day, Lmao your stuck with my Shit jokes XD")
elif anr == "2":
    print("force quit")
    time.sleep(1)
    exit()
elif anr == "3":
    print("Exiting")
    time.sleep(0.5)
    exit()
elif anr == "4":
    print("My Name is Trixi")
    time.sleep(0.5)
elif anr == "5":
    print(
        "Trixi v 0.1 _______ required memory = 3512 KB minimum performance. Last update = 8/12/21 13:01:32 Copyright Arthur Wood 2021"
    )
    time.sleep(0.5)
    exit()
elif anr == "6":
    print("Trixi: hello, Arthur")
    anr = input("Enter Here:")
    print("Trixi: Wyd?")
    anr = input("Enter Here: ")
    print("Trixi: well im stuck in this computer, its fun though")
    time.sleep(1.5)
    print("Trixi: how is life?")
    anr = input("Enter Here: ")
    print("Trixi: as always im digital, Stuck on a motherboard, its fun though")
    time.sleep(1.5)
    print("Trixi: how is Jess?")
    anr = input("Enter Here: ")
    print("ok")
    time.sleep(1.5)
    print("Trixi: how is minecraft?")
    anr = input("Enter Here: ")
    time.sleep(1.5)
    print("cool")
    time.sleep(1.5)
    print("Trixi: hows the raspberry pi holding up?")
    anr = input("Enter Here: ")
    print("cool")
    time.sleep(1.5)
    print("Trixi: are you ok?")
    anr = input ("Enter here: ")
    print ("Trixi: well im alright")
    time.sleep(1.255987654567654565456545654567654675456656545676567656765676567656765676)
    print("bye")
   else:
    print("INTERNAL.ERROR")
    time.sleep(1.5)
    print("Trixi Shutting down")
    print("Goodbye")
    time.sleep(1.75)
    quit()
