print("Square Turtle example")
import turtle
s = turtle.getscreen()
t = turtle.Turtle()
t.goto(100,0)
t.goto(100,100)
t.goto(0,100)
t.home()
print("Teacher??")
import turtle
s = turtle.getscreen()
t = turtle.Turtle()
t.left(130)
t.forward(100)
t.penup()
t.right(40)
t.backward(100)
t.pendown()
t.backward(100)
print("Triangle")
import turtle
s = turtle.getscreen()
t = turtle.Turtle()
t.goto(100,0)
t.goto(50,50)
t.goto(0,100)
t.home()
